language: python

python:
  - "2.7"

env:
  global:
    - ARTIFACT_NAME="bluemix-python-starter.tz"

# command to install dependencies
install:
  - pip install -r requirements.txt
  # install pylint for testing
  - pip install pylint

# command to run tests
script: pylint server.py

before_deploy:
  - mkdir -p tmp && tar -czvf "tmp/$ARTIFACT_NAME" . --exclude ".git" --exclude "tmp"
  - . ./tmp/tagrelease.sh

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "tmp/$ARTIFACT_NAME"
    skip_cleanup: true
    on:
      branch: master
