language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  # install pylint for testing
  - pip install pylint

# command to run tests
script: pylint server.py
